name: CI
on:
  push:
    branches:
      - "main"
  pull_request:


jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Stylua check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          # token is needed because the action allegedly downloads binary from github releases
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --check .
          version: latest
  release:
    name: release

    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - stylua
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: colorscheme-randomizer.nvim
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Current stable release: ${{ steps.release.outputs.tag_name }}"
          tag_exists_error: false
          force_push_tag: true
