name: CI
on:
  push:
    branches:
      - "main"
  pull_request:


jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Stylua check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          # token is needed because the action allegedly downloads binary from github releases
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --check .
          version: latest
  docs:
    runs-on: ubuntu-latest
    needs: stylua
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: colorscheme-randomizer.nvim
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  release:
    name: release

    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - stylua
      - docs
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: colorscheme-randomizer.nvim
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Current stable release: ${{ steps.release.outputs.tag_name }}"
          tag_exists_error: false
          force_push_tag: true
