name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v6.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 15
        days-before-close: 5
        stale-issue-message: >
          This issue has been automatically marked as stale. **If this issue is still affecting you, please leave any comment** (for example, "bump"), and we'll keep it open. If you have any new additional information—in particular, if this is still reproducible in the [latest version of Electron](https://www.electronjs.org/releases/stable) or in the [beta](https://www.electronjs.org/releases/beta)—please include it with your comment!
        close-issue-message: >
          This issue has been closed due to inactivity, and will not be monitored.  If this is a bug and you can reproduce this issue on a [supported version of Electron](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline) please open a new issue and include instructions for reproducing the issue.
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        exempt-issue-labels: 'blocked'
        exempt-pr-labels: 'blocked,WIP'
